version: '3.8'

volumes:
  laravel-app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./laravel-test

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./extra:/usr/local/apache2/conf/extra
      - laravel-app:/var/www/laravel-test
      - ./logs:/var/logs
  php:
    image: php:7.4-fpm
    volumes:
      - laravel-app:/var/www/laravel-test